#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录

# 应用服务 WEB 访问端口
server:
  port:8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studata?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: database123
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  type-aliases-package:com.example.springweb.mybatis.entity
#  mapper-locations:classpath:mappers/*xml